### ISSUE TITLE
React: PortfolioPage

### ISSUE THREAD

**Issue by Adrian-gh1** [Mandeepan/RobinhoodClone#16]
https://docs.google.com/spreadsheets/d/1rwQFSUgueG-fn-eo3Bj25W2_zKIYQ6Bo6QACXfGng-A/edit?gid=1164314137#gid=1164314137

**Comment by Mandeepan** [comment]
- [x] user info, cash balances, portfolio value, and total balance
- [x] add fund
- [x] liquidate portfolio
- [x] display list of user portfolio stocks, and updated price, and market value
- [x] css for the page
