### ISSUE TITLE
bug when trying to log out inside of portfolio page and stock details page

### ISSUE THREAD

**Issue by QuentinPace** [Mandeepan/RobinhoodClone#23]

**Comment by Mandeepan** [comment]
- [x] Portfolio Page logout bug fixed : reverse order of useEffect & `if (!sessionUser) {
        return <Navigate to='/login'></Navigate>
    }`

**Comment by Mandeepan** [comment]
- [x] SpotDetailPage need to include `if (!sessionUser) {
        return <Navigate to='/login'></Navigate>
    }`
